#!/usr/bin/env node
/**
 * tasksStatusBoard.cjs (reconstructed clean version)
 * Generates status dashboard artifacts (Markdown, HTML, bundled self‑contained HTML) from tasks_all.json
 * Includes: deltas, trend chart (line & stacked), legend toggle w/ persistence, virtualization, exports, theme toggle.
 */
const fs = require('fs');
const path = require('path');

// ---------------- Data Loading & Normalization ----------------
function loadAll(){
  const p=path.resolve(process.cwd(),'tasks_all.json');
  if(!fs.existsSync(p)){ console.error('tasks_all.json not found'); process.exit(1);} 
  const raw=JSON.parse(fs.readFileSync(p,'utf8'));
  const tasks=Array.isArray(raw)?raw:(raw.tasks||[]);
  return tasks.map(t=>({
    id:t.id,
    title:t.title||'',
    status:t.status||'UNKNOWN',
    category:t.category||t.type||'UNCATEGORIZED',
    priorityScore:Number(t.priorityScore)||0,
    riskScore:Number(t.riskScore)||0,
    impactScore:Number(t.impactScore)||0,
    userStory:t.userStory||'',
    acceptanceCriteria:t.acceptanceCriteria||[],
    createdAt:t.createdAt||null,
    updatedAt:t.updatedAt||null,
    dependencies:t.dependencies||[],
    hasCodeRefs:t.hasCodeRefs||false
  }));
}

const NORM_MAP={SPEC:'PLANNED',DERIVED:'PLANNED',FUTURE:'BACKLOG',TODO:'READY',IMPL:'IN_PROGRESS',DONE:'COMPLETE',COMPLETE:'COMPLETE'};
function normalizeStatus(s){ return NORM_MAP[s]||s; }

function aggregate(tasks){
  const rawCounts={}, normCounts={};
  for(const t of tasks){
    rawCounts[t.status]=(rawCounts[t.status]||0)+1;
    const norm=normalizeStatus(t.status);
    normCounts[norm]=(normCounts[norm]||0)+1;
  }
  return {rawCounts,normCounts,total:tasks.length};
}

function ensureArtifacts(){ const dir=path.resolve(process.cwd(),'artifacts'); if(!fs.existsSync(dir)) fs.mkdirSync(dir,{recursive:true}); return dir; }
function formatNum(n){ return (typeof n==='number'&&!isNaN(n))?Number(n).toFixed(2):'0.00'; }
function loadKpiIfPresent(){ const p=path.resolve(process.cwd(),'artifacts','tasks-kpi.json'); if(fs.existsSync(p)){ try{return JSON.parse(fs.readFileSync(p,'utf8'));}catch{ return null; } } return null; }

// ---------------- History Handling ----------------
function loadHistory(){ const p=path.resolve(process.cwd(),'artifacts','tasks-status-board-history.json'); if(!fs.existsSync(p)) return []; try{return JSON.parse(fs.readFileSync(p,'utf8'));}catch{return [];} }
function appendHistory(agg, history){ const snap={timestamp:new Date().toISOString(),rawCounts:agg.rawCounts,normCounts:agg.normCounts,total:agg.total}; const newHist=[...history,snap]; fs.writeFileSync(path.resolve(process.cwd(),'artifacts','tasks-status-board-history.json'), JSON.stringify(newHist,null,2),'utf8'); return newHist; }
function computeDeltas(currentAgg, prevSnap){ if(!prevSnap) return {raw:{},norm:{},prevRaw:{},prevNorm:{}}; const rawDelta={}, normDelta={}; const prevRaw=prevSnap.rawCounts||{}, prevNorm=prevSnap.normCounts||{}; for(const [k,v] of Object.entries(currentAgg.rawCounts)) rawDelta[k]=v-(prevRaw[k]||0); for(const [k,v] of Object.entries(currentAgg.normCounts)) normDelta[k]=v-(prevNorm[k]||0); return {raw:rawDelta,norm:normDelta,prevRaw,prevNorm}; }

// ---------------- Detail Pages ----------------
function escapeHtml(str){ return (str||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c])); }
function writeTaskDetails(tasks){ const dir=ensureArtifacts(); const tdDir=path.join(dir,'task-details'); if(!fs.existsSync(tdDir)) fs.mkdirSync(tdDir,{recursive:true}); for(const t of tasks){ const html=`<!DOCTYPE html><html><head><meta charset="UTF-8"/><title>Task ${t.id}</title><style>body{font-family:system-ui,Arial,sans-serif;padding:1rem;line-height:1.35}pre{white-space:pre-wrap;background:#f5f5f5;padding:.5rem;border:1px solid #ccc}table{border-collapse:collapse}td,th{padding:4px 6px;border:1px solid #ccc;font-size:13px}</style></head><body><h1>Task ${t.id}</h1><table><tbody><tr><th>Title</th><td>${escapeHtml(t.title)}</td></tr><tr><th>Status</th><td>${escapeHtml(t.status)}</td></tr><tr><th>Normalized</th><td>${normalizeStatus(t.status)}</td></tr><tr><th>Category</th><td>${escapeHtml(t.category)}</td></tr><tr><th>Priority</th><td>${formatNum(t.priorityScore)}</td></tr><tr><th>Risk</th><td>${formatNum(t.riskScore)}</td></tr><tr><th>Impact</th><td>${formatNum(t.impactScore)}</td></tr><tr><th>Created</th><td>${escapeHtml(t.createdAt||'')}</td></tr><tr><th>Updated</th><td>${escapeHtml(t.updatedAt||'')}</td></tr><tr><th>Deps</th><td>${(t.dependencies||[]).join(', ')||'-'}</td></tr><tr><th>Has Code Refs</th><td>${t.hasCodeRefs?'yes':'no'}</td></tr></tbody></table><h2>User Story</h2><pre>${escapeHtml(t.userStory||'')}</pre><h2>Acceptance Criteria</h2><ul>${(t.acceptanceCriteria||[]).map(c=>'<li>'+escapeHtml(c)+'</li>').join('')||'<li>-</li>'}</ul></body></html>`; fs.writeFileSync(path.join(tdDir,`${t.id}.html`),html,'utf8'); } }

// ---------------- Markdown ----------------
function toMarkdown(tasks, agg, kpi, deltas){ const lines=[]; lines.push('# Tasks Status Board'); lines.push(`Generated: ${new Date().toISOString()}`); lines.push(`Total Tasks: ${agg.total}`); if(kpi){ lines.push('\n## KPI Snapshot'); lines.push(`- Actionable Completion %: ${kpi.actionableCompletePct.toFixed(2)}%`); lines.push(`- Backlog Ratio: ${kpi.backlogRatio.toFixed(2)}%`); if(kpi.priorityStats){ lines.push(`- Priority p50: ${kpi.priorityStats.p50.toFixed(2)}`); lines.push(`- Priority p90: ${kpi.priorityStats.p90.toFixed(2)}`);} } lines.push('\n## Raw Status Distribution'); lines.push('| Status | Count | Percent | Δ Count | Δ % |'); lines.push('|--------|-------|---------|---------|-----|'); Object.keys(agg.rawCounts).sort().forEach(s=>{ const c=agg.rawCounts[s]; const d=deltas&&deltas.raw?(deltas.raw[s]||0):0; const prev=deltas&&deltas.prevRaw?(deltas.prevRaw[s]||0):0; const pctDelta=prev?((c-prev)*100/prev).toFixed(2)+'%':(prev===0&&c>0?'∞':'0.00%'); const deltaStr=d===0?'':(d>0?`+${d}`:`${d}`); lines.push(`| ${s} | ${c} | ${(c*100/agg.total).toFixed(2)}% | ${deltaStr} | ${pctDelta} |`); }); lines.push('\n## Normalized Status Distribution'); lines.push('| Status | Count | Percent | Δ Count | Δ % |'); lines.push('|--------|-------|---------|---------|-----|'); Object.keys(agg.normCounts).sort().forEach(s=>{ const c=agg.normCounts[s]; const d=deltas&&deltas.norm?(deltas.norm[s]||0):0; const prev=deltas&&deltas.prevNorm?(deltas.prevNorm[s]||0):0; const pctDelta=prev?((c-prev)*100/prev).toFixed(2)+'%':(prev===0&&c>0?'∞':'0.00%'); const deltaStr=d===0?'':(d>0?`+${d}`:`${d}`); lines.push(`| ${s} | ${c} | ${(c*100/agg.total).toFixed(2)}% | ${deltaStr} | ${pctDelta} |`); }); lines.push('\n## Tasks Table'); lines.push('| ID | Title | Category | Raw | Normalized | Priority |'); lines.push('|----|-------|----------|-----|------------|----------|'); tasks.forEach(t=>lines.push(`| ${t.id} | ${t.title.replace(/\|/g,'\\|')} | ${t.category} | ${t.status} | ${normalizeStatus(t.status)} | ${formatNum(t.priorityScore)} |`)); return lines.join('\n'); }

// ---------------- HTML Generation ----------------
function options(list){ return list.sort().map(v=>`<option value="${v}">${v}</option>`).join(''); }
function toHtml(tasks, agg, kpi, deltas, history, opts={bundled:false,b64:null}){
  function deltaBadge(kind,status){ if(!deltas) return ''; const src=kind==='raw'?deltas.raw:deltas.norm; const prevSrc=kind==='raw'?deltas.prevRaw:deltas.prevNorm; if(!src) return ''; const d=src[status]||0; const prev=prevSrc?(prevSrc[status]||0):0; let pct; if(prev===0){ pct=d>0?'∞':'0.00%'; } else { const newVal=prev+d; pct=((newVal-prev)*100/prev).toFixed(2)+'%'; } const cls=d===0?'neutral':(d>0?'up':'down'); const countStr=d===0?'0':`${d>0?'+':''}${d}`; return `<span class="delta ${cls}" title="Δ Count: ${countStr} | Δ %: ${pct}">${countStr}<span class="delta-pct"> (${pct})</span></span>`; }
  const rawRows=Object.entries(agg.rawCounts).sort().map(([s,c])=>{ const pct=(c*100/agg.total).toFixed(2)+'%'; return `<tr><td>${s}</td><td>${c} ${deltaBadge('raw',s)}</td><td>${pct}</td></tr>`; }).join('');
  const normRows=Object.entries(agg.normCounts).sort().map(([s,c])=>{ const pct=(c*100/agg.total).toFixed(2)+'%'; return `<tr><td>${s}</td><td>${c} ${deltaBadge('norm',s)}</td><td>${pct}</td></tr>`; }).join('');
  const kpiBlock=kpi?`<section><h2>KPI Snapshot</h2><ul><li>Total: ${kpi.total}</li><li>Actionable Completion %: ${kpi.actionableCompletePct.toFixed(2)}%</li><li>Backlog Ratio: ${kpi.backlogRatio.toFixed(2)}%</li>${kpi.priorityStats?`<li>Priority p50: ${kpi.priorityStats.p50.toFixed(2)}</li><li>Priority p90: ${kpi.priorityStats.p90.toFixed(2)}</li>`:''}</ul></section>`:'';
  const dataJson=JSON.stringify(tasks.map(t=>({id:t.id,title:t.title,category:t.category,status:t.status,norm:normalizeStatus(t.status),priorityScore:formatNum(t.priorityScore)})));
  const historyJson=JSON.stringify(history||[]);
  const parts=[]; parts.push('<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><title>Tasks Status Board</title><meta name="viewport" content="width=device-width,initial-scale=1"/>');
  parts.push('<style>:root{--bg:#ffffff;--fg:#111;--border:#ccc;--thead:#f5f5f5;--accent:#0366d6;--shadow:rgba(0,0,0,0.15);--badge-up:#0a0;--badge-down:#c00;--badge-neutral:#777;}[data-theme=dark]{--bg:#1e1f24;--fg:#e6e6e6;--border:#444;--thead:#2a2c33;--accent:#4ea1ff;--shadow:rgba(0,0,0,0.6);--badge-up:#3ddc7a;--badge-down:#ff6b6b;--badge-neutral:#999;}body{font-family:system-ui,Arial,sans-serif;margin:1.25rem;background:var(--bg);color:var(--fg);}table{border-collapse:collapse;width:100%;margin-bottom:1.5rem;box-shadow:0 1px 3px var(--shadow);}th,td{border:1px solid var(--border);padding:4px 6px;font-size:12px;}th{background:var(--thead);position:sticky;top:0;cursor:pointer}caption{font-weight:600;margin-bottom:.5rem}.filters{display:flex;gap:.75rem;flex-wrap:wrap;margin:1rem 0}input,select,button{padding:4px 6px;font-size:12px;border:1px solid var(--border);background:var(--bg);color:var(--fg);}button{cursor:pointer}.norm{padding:2px 6px;border-radius:10px;font-size:11px;font-weight:500;display:inline-block}.norm-PLANNED{background:#4e79a7;color:#fff}.norm-BACKLOG{background:#9aa0a6;color:#fff}.norm-READY{background:#59a14f;color:#fff}.norm-IN_PROGRESS{background:#f28e2b;color:#fff}.norm-COMPLETE{background:#8cd17d;color:#000}#exports{margin:1rem 0}.delta{font-size:10px;margin-left:4px;white-space:nowrap}.delta .delta-pct{opacity:.75;font-size:9px}.delta.up{color:var(--badge-up)}.delta.down{color:var(--badge-down)}.delta.neutral{color:var(--badge-neutral)}.table-viewport{height:600px;overflow:auto;border:1px solid var(--border);box-shadow:0 1px 3px var(--shadow);} .spacer{height:0} canvas#trend{width:100%;max-width:900px;border:1px solid var(--border);background:var(--bg);margin:0 0 .6rem} #trendLegend{display:flex;flex-wrap:wrap;gap:.4rem;margin:0 0 1rem;font-size:11px} .legend-item{display:inline-flex;align-items:center;gap:4px;padding:2px 8px;border:1px solid var(--border);border-radius:14px;background:var(--bg);line-height:1;user-select:none;transition:opacity .15s,background .15s} .legend-item .legend-swatch{width:12px;height:12px;border-radius:3px;box-shadow:0 0 0 1px rgba(0,0,0,.18)} .legend-item.hidden{opacity:.32} .legend-item:focus{outline:2px solid var(--accent);outline-offset:2px}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap;border:0}</style>');
  parts.push('</head><body>');
  parts.push('<div style="display:flex;align-items:center;gap:.75rem;flex-wrap:wrap"><h1 style="margin:0">Tasks Status Board</h1><button id="themeToggle" type="button">Toggle Theme</button></div>');
  parts.push(`<p>Generated: ${new Date().toISOString()} &mdash; Total: ${agg.total}</p>`); if(kpiBlock) parts.push(kpiBlock);
  parts.push('<h2>Raw Status Distribution</h2><table id="rawDist"><thead><tr><th>Status</th><th>Count Δ</th><th>Percent</th></tr></thead><tbody>'+rawRows+'</tbody></table>');
  parts.push('<h2>Normalized Lifecycle Distribution</h2><table id="normDist"><thead><tr><th>Status</th><th>Count Δ</th><th>Percent</th></tr></thead><tbody>'+normRows+'</tbody></table>');
  parts.push('<h2>Trend (Normalized Status Counts)</h2><p class="sr-only" id="legendHelp">Trend legend: use arrow keys to move between series buttons and Space or Enter to toggle visibility. Use Show All, Hide All, or Invert buttons for bulk operations.</p><canvas id="trend" height="170"></canvas><div style="display:flex;gap:.5rem;flex-wrap:wrap;align-items:center;margin:.25rem 0 .5rem"><div id="legendBulk" role="group" aria-label="Legend bulk actions"><button id="legendShowAll" type="button">Show All</button><button id="legendHideAll" type="button">Hide All</button><button id="legendInvert" type="button">Invert</button></div></div><div id="trendLegend" role="toolbar" aria-labelledby="legendHelp" aria-description="Toggle visibility of status series on the trend chart"></div><div id="trendAnnouncer" class="sr-only" aria-live="polite"></div>');
  parts.push('<div class="filters"><input id="search" placeholder="Search title/category..." /><select id="rawFilter"><option value="">Raw Status</option>'+options(Object.keys(agg.rawCounts))+'</select><select id="normFilter"><option value="">Normalized</option>'+options(Object.keys(agg.normCounts))+'</select><button id="clear">Clear</button><div id="exports"><button id="exportCsv">Export CSV</button><button id="exportJson">Export JSON</button><button id="exportHistoryCsv">History CSV</button><button id="trendMode">Mode: Line</button><button id="autoRefresh">Auto Refresh: Off</button></div></div>');
  parts.push('<div class="table-viewport" id="viewport"><table id="tasks"><thead><tr><th data-key="id">ID</th><th data-key="title">Title</th><th data-key="category">Category</th><th data-key="status">Raw</th><th data-key="norm">Norm</th><th data-key="priorityScore">Priority</th></tr></thead><tbody></tbody></table></div>');
  if(opts.bundled&&opts.b64){ parts.push(`<script id="__B64__" type="application/octet-stream">${opts.b64}</script>`);} else { parts.push(`<script id="__DATA__" type="application/json">${dataJson}</script>`); parts.push(`<script id="__HISTORY__" type="application/json">${historyJson}</script>`);} 
  const clientScript = `(()=> {
  const ROW_HEIGHT=26; const viewport=document.getElementById('viewport'); const isBundled=!!document.getElementById('__B64__');
  const STATUS_COLORS={PLANNED:'#4e79a7',BACKLOG:'#9aa0a6',READY:'#59a14f',IN_PROGRESS:'#f28e2b',COMPLETE:'#8cd17d'}; const HIDDEN_KEY='tasksBoardHiddenSeries';
  function getEmbedded(){ const b64=document.getElementById('__B64__'); if(b64){ try{ const d=JSON.parse(atob(b64.textContent.trim())); return {tasks:d.tasks,history:d.history||[]}; }catch(e){ return {tasks:[],history:[]}; } } const tasks=JSON.parse(document.getElementById('__DATA__').textContent); const hist=JSON.parse(document.getElementById('__HISTORY__').textContent||'[]'); return {tasks,history:hist}; }
  const embedded=getEmbedded(); let data=embedded.tasks.slice(); const history=embedded.history;
  const S=document.getElementById('search'),R=document.getElementById('rawFilter'),N=document.getElementById('normFilter'),C=document.getElementById('clear'); const tbody=document.querySelector('#tasks tbody'); let state={k:null,d:1,filtered:data};
  let savedState; try{ savedState=JSON.parse(localStorage.getItem('tasksBoardState')||'{}'); }catch{} if(savedState){ if(savedState.search) S.value=savedState.search; if(savedState.raw) R.value=savedState.raw; if(savedState.norm) N.value=savedState.norm; if(savedState.sortKey){ state.k=savedState.sortKey; state.d=savedState.sortDir||1; } }
  function persist(){ try{ localStorage.setItem('tasksBoardState', JSON.stringify({search:S.value,raw:R.value,norm:N.value,sortKey:state.k,sortDir:state.d})); }catch{} }
  function applyFilters(){ const q=S.value.toLowerCase(), r=R.value, n=N.value; state.filtered=data.filter(t=>{ if(q && !(t.title.toLowerCase().includes(q)||t.category.toLowerCase().includes(q))) return false; if(r && t.status!==r) return false; if(n && t.norm!==n) return false; return true; }); persist(); render(); }
  [S,R,N].forEach(el=>el.addEventListener('input',applyFilters)); C.addEventListener('click',()=>{ S.value=''; R.value=''; N.value=''; applyFilters(); });
  function sort(k){ if(state.k===k) state.d*=-1; else { state.k=k; state.d=1;} const dir=state.d; const numFields=new Set(['id','priorityScore']); state.filtered.sort((a,b)=>{ let av=a[k],bv=b[k]; if(numFields.has(k)){ av=parseFloat(av); bv=parseFloat(bv);} if(av<bv) return -1*dir; if(av>bv) return 1*dir; return 0; }); persist(); render(true);}
  document.querySelectorAll('#tasks thead th').forEach(th=>{ const k=th.getAttribute('data-key'); if(k) th.addEventListener('click',()=>sort(k)); });
  function esc(s){ return (s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c])); }
  function rowHtml(t){ return '<tr data-status="'+t.status+'" data-norm="'+t.norm+'"><td>'+t.id+'</td><td><a href="task-details/'+t.id+'.html" target="_blank">'+esc(t.title)+'</a></td><td>'+esc(t.category)+'</td><td>'+t.status+'</td><td><span class="norm norm-'+t.norm+'">'+t.norm+'</span></td><td>'+t.priorityScore+'</td></tr>'; }
  function render(reset){ if(reset) viewport.scrollTop=0; const vh=viewport.clientHeight; const st=viewport.scrollTop; const start=Math.floor(st/ROW_HEIGHT); const visible=Math.ceil(vh/ROW_HEIGHT)+5; const end=Math.min(start+visible,state.filtered.length); const beforeH=start*ROW_HEIGHT; const afterH=(state.filtered.length-end)*ROW_HEIGHT; let html='<tr class="spacer" style="height:'+beforeH+'px"></tr>'; for(let i=start;i<end;i++) html+=rowHtml(state.filtered[i]); html+='<tr class="spacer" style="height:'+afterH+'px"></tr>'; tbody.innerHTML=html; }
  viewport.addEventListener('scroll',()=>render());
  function currentRows(){ return state.filtered; }
  document.getElementById('exportCsv').addEventListener('click',()=>{ const d=currentRows(); if(!d.length) return; const header=Object.keys(d[0]); const csv=[header.join(','), ...d.map(o=>header.map(k=>'"'+String(o[k]||'').replace(/"/g,'""')+'"').join(','))].join('\n'); const blob=new Blob([csv],{type:'text/csv'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='tasks-export.csv'; a.click(); });
  document.getElementById('exportJson').addEventListener('click',()=>{ const d=currentRows(); const blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='tasks-export.json'; a.click(); });
  const histBtn=document.getElementById('exportHistoryCsv'); if(histBtn){ histBtn.addEventListener('click',()=>{ if(!history.length) return; const keys=[...history.reduce((s,h)=>{ Object.keys(h.normCounts).forEach(k=>s.add(k)); return s; }, new Set())].sort(); const header=['timestamp',...keys]; const rows=history.map(h=>[h.timestamp,...keys.map(k=>h.normCounts[k]||0)]); const csv=[header.join(','), ...rows.map(r=>r.join(','))].join('\n'); const blob=new Blob([csv],{type:'text/csv'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='tasks-history.csv'; a.click(); }); }
  let trendMode=localStorage.getItem('tasksBoardTrendMode')||'line'; const trendBtn=document.getElementById('trendMode'); function updateTrendBtn(){ if(trendBtn) trendBtn.textContent='Mode: '+(trendMode==='stacked'?'Stacked':'Line'); } updateTrendBtn(); if(trendBtn){ trendBtn.addEventListener('click',()=>{ trendMode=trendMode==='line'?'stacked':'line'; localStorage.setItem('tasksBoardTrendMode',trendMode); updateTrendBtn(); drawTrend(); }); }
  const autoBtn=document.getElementById('autoRefresh'); let autoOn=false; function updateAuto(){ if(autoBtn) autoBtn.textContent='Auto Refresh: '+(autoOn?'On':'Off'); } if(autoBtn){ autoBtn.addEventListener('click',()=>{ autoOn=!autoOn; updateAuto(); if(autoOn) startPolling(); else if(autoTimer) clearInterval(autoTimer); }); updateAuto(); } let autoTimer=null; function startPolling(){ if(isBundled) return; if(autoTimer) clearInterval(autoTimer); autoTimer=setInterval(async()=>{ try{ const res=await fetch('tasks-status-board-history.json?ts='+Date.now(),{cache:'no-store'}); if(!res.ok) return; const arr=await res.json(); if(Array.isArray(arr)&&arr.length>history.length){ location.reload(); } }catch(e){} },10000); }
  function loadHidden(){ try{return JSON.parse(localStorage.getItem(HIDDEN_KEY)||'[]');}catch{return [];} } let hiddenStatuses=new Set(loadHidden()); function persistHidden(){ try{ localStorage.setItem(HIDDEN_KEY, JSON.stringify([...hiddenStatuses])); }catch{} }
  function buildLegend(){ const el=document.getElementById('trendLegend'); if(!el||!history.length) return; const keys=[...history.reduce((s,h)=>{ Object.keys(h.normCounts).forEach(k=>s.add(k)); return s; }, new Set())].sort(); el.innerHTML=keys.map(k=>{ const vis=!hiddenStatuses.has(k); return '<button type="button" class="legend-item'+(vis?'':' hidden')+'" data-status="'+k+'" aria-pressed="'+vis+'" aria-label="Toggle '+k+' series" title="Toggle '+k+' series"><span class="legend-swatch" style="background:'+(STATUS_COLORS[k]||'#666')+'"></span><span class="legend-label">'+k+'</span></button>'; }).join(''); const announcer=document.getElementById('trendAnnouncer'); const btns=[...el.querySelectorAll('.legend-item')]; function announce(msg){ if(announcer) announcer.textContent=msg; }
  btns.forEach((btn,i)=>{ function toggle(){ const st=btn.getAttribute('data-status'); const wasHidden=hiddenStatuses.has(st); if(wasHidden) hiddenStatuses.delete(st); else hiddenStatuses.add(st); persistHidden(); btn.classList.toggle('hidden'); btn.setAttribute('aria-pressed', String(!hiddenStatuses.has(st))); announce(wasHidden?('Showing '+st+' series'):('Hid '+st+' series')); drawTrend(); }
    btn.addEventListener('click',toggle);
    btn.addEventListener('keydown',e=>{ if(['ArrowRight','ArrowDown'].includes(e.key)){ e.preventDefault(); btns[(i+1)%btns.length].focus(); } else if(['ArrowLeft','ArrowUp'].includes(e.key)){ e.preventDefault(); btns[(i-1+btns.length)%btns.length].focus(); } else if(e.key==='Home'){ e.preventDefault(); btns[0].focus(); } else if(e.key==='End'){ e.preventDefault(); btns[btns.length-1].focus(); } else if(e.key===' '){ e.preventDefault(); toggle(); } });
  });
  // Bulk controls
  const showAll=document.getElementById('legendShowAll');
  const hideAll=document.getElementById('legendHideAll');
  const invert=document.getElementById('legendInvert');
  function rebuildAfterBulk(){ persistHidden(); buildLegend(); drawTrend(); }
  if(showAll) showAll.onclick=()=>{ hiddenStatuses.clear(); announce('Showing all series'); rebuildAfterBulk(); };
  if(hideAll) hideAll.onclick=()=>{ const all=keys; hiddenStatuses=new Set(all); announce('Hid all series'); rebuildAfterBulk(); };
  if(invert) invert.onclick=()=>{ const all=keys; const newSet=new Set(); all.forEach(k=>{ if(!hiddenStatuses.has(k)) newSet.add(k); }); hiddenStatuses=newSet; announce('Inverted series visibility'); rebuildAfterBulk(); };
  }
  function drawTrend(){ const canvas=document.getElementById('trend'); if(!canvas||!history.length) return; const ctx=canvas.getContext('2d'); const W=canvas.width=canvas.clientWidth; const H=canvas.height; ctx.clearRect(0,0,W,H); const keys=[...history.reduce((s,h)=>{ Object.keys(h.normCounts).forEach(k=>s.add(k)); return s; }, new Set())].sort(); let max; if(trendMode==='stacked'){ max=Math.max(...history.map(h=>keys.reduce((sum,k)=>sum+(hiddenStatuses.has(k)?0:(h.normCounts[k]||0)),0))); } else { max=Math.max(...history.map(h=> Math.max(...keys.filter(k=>!hiddenStatuses.has(k)).map(k=>h.normCounts[k]||0)))); if(!isFinite(max)||max<=0) max=1; } const leftPad=40, bottomPad=18; ctx.strokeStyle='#888'; ctx.beginPath(); ctx.moveTo(leftPad,5); ctx.lineTo(leftPad,H-bottomPad); ctx.lineTo(W-5,H-bottomPad); ctx.stroke(); if(trendMode==='stacked'){ const stacked=history.map(h=>{ let run=0; const layer={}; keys.forEach(k=>{ const v=hiddenStatuses.has(k)?0:(h.normCounts[k]||0); run+=v; layer[k]=run; }); return {layer}; }); keys.forEach(k=>{ if(hiddenStatuses.has(k)) return; const color=STATUS_COLORS[k]||'#666'; ctx.fillStyle=color; ctx.globalAlpha=.34; ctx.beginPath(); history.forEach((h,i)=>{ const x=leftPad+((W-leftPad-10)*(i/(history.length-1||1))); const top=stacked[i].layer[k]; const y=H-bottomPad-(top/max)*(H-bottomPad-10); if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y); }); for(let i=history.length-1;i>=0;i--){ const x=leftPad+((W-leftPad-10)*(i/(history.length-1||1))); const prev=stacked[i].layer[k]-(hiddenStatuses.has(k)?0:(history[i].normCounts[k]||0)); const yPrev=H-bottomPad-(prev/max)*(H-bottomPad-10); ctx.lineTo(x,yPrev); } ctx.closePath(); ctx.fill(); ctx.globalAlpha=1; ctx.strokeStyle=color; ctx.beginPath(); history.forEach((h,i)=>{ const x=leftPad+((W-leftPad-10)*(i/(history.length-1||1))); const top=stacked[i].layer[k]; const y=H-bottomPad-(top/max)*(H-bottomPad-10); if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y); }); ctx.stroke(); }); } else { keys.forEach(k=>{ if(hiddenStatuses.has(k)) return; const color=STATUS_COLORS[k]||'#666'; ctx.strokeStyle=color; ctx.beginPath(); history.forEach((h,i)=>{ const x=leftPad+((W-leftPad-10)*(i/(history.length-1||1))); const y=H-bottomPad-((h.normCounts[k]||0)/max)*(H-bottomPad-10); if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y); }); ctx.stroke(); }); } ctx.font='10px system-ui'; ctx.fillStyle='var(--fg)'; ctx.textAlign='right'; ctx.fillText(max,leftPad-4,10); ctx.fillText('0',leftPad-4,H-bottomPad); }
  const themeBtn=document.getElementById('themeToggle'); function applyTheme(t){ document.documentElement.setAttribute('data-theme',t); localStorage.setItem('tasksBoardTheme',t);} const savedTheme=localStorage.getItem('tasksBoardTheme')||'light'; applyTheme(savedTheme); themeBtn.addEventListener('click',()=>{ const cur=document.documentElement.getAttribute('data-theme')==='dark'?'dark':'light'; applyTheme(cur==='dark'?'light':'dark'); });
  applyFilters(); if(savedState && savedState.sortKey){ sort(savedState.sortKey);} buildLegend(); drawTrend(); window.addEventListener('resize',drawTrend);
})();`;
  parts.push(`<script>${clientScript}</script>`);
  parts.push('</body></html>');
  return parts.join('\n');
}

function buildBundled(tasks, agg, kpi, deltas, history){ const payload={tasks:tasks.map(t=>({id:t.id,title:t.title,category:t.category,status:t.status,norm:normalizeStatus(t.status),priorityScore:formatNum(t.priorityScore)})), history, kpi}; const b64=Buffer.from(JSON.stringify(payload)).toString('base64'); return toHtml(tasks, agg, kpi, deltas, history, {bundled:true,b64}); }

// ---------------- Main ----------------
function main(){ const tasks=loadAll(); let history=loadHistory(); const prev=history.length?history[history.length-1]:null; const agg=aggregate(tasks); const deltas=computeDeltas(agg, prev); const kpi=loadKpiIfPresent(); const md=toMarkdown(tasks, agg, kpi, deltas); history=appendHistory(agg, history); const html=toHtml(tasks, agg, kpi, deltas, history); const bundled=buildBundled(tasks, agg, kpi, deltas, history); const dir=ensureArtifacts(); fs.writeFileSync(path.join(dir,'tasks-status-board.md'), md,'utf8'); fs.writeFileSync(path.join(dir,'tasks-status-board.html'), html,'utf8'); fs.writeFileSync(path.join(dir,'tasks-board.bundle.html'), bundled,'utf8'); writeTaskDetails(tasks); console.log('Generated tasks-status-board.{md,html}, tasks-board.bundle.html + task-details + history (updated) in artifacts/'); }

main();
